[package]
name = "shuriken16"
version = "0.1.0"
authors = ["Rusty Wagner <rusty@vector35.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
hex = "0.3.2"
byteorder = "1.2.4"

[dependencies.sdl2]
version = "0.31.0"
default-features = false
features = ["unsafe_textures"]
